### ISSUE TITLE
Path to the mylake.Rdata file

### ISSUE THREAD

**Issue by jjvenky** [aemon-j/MyLakeR#6]
Hi,

I was testing something out with only MyLakeR and not the entire LakeEnsemblR and came across this problem of file location. The `config_mylake` function wants to look for the `mylake_config_template.Rdata` file but the path is wrong since that file is only in the LakeEnsemblR package.

```
> config_mylake(config_file="Vansjo_master_config.yaml",
+               folder=file.path(mylake_path,"extdata","example"))
Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
In addition: Warning message:
In readChar(con, 5L, useBytes = TRUE) :
  cannot open compressed file '/home/jason/R/x86_64-pc-linux-gnu-library/4.1/MyLakeR/extdata/mylake_config_template.Rdata', probable reason 'No such file or directory'
```

Should that Rdata file be installed with MyLakeR or pulled over from LakeEnsemblR as an Imports in the DESCRIPTION file?

Thoughts?

**Comment by rmpilla** [comment]
It looks like the config_mylake function still used the previous name of the MyLake config file. We renamed it to "mylake.Rdata" a while back, and this occurrence was overlooked. I just committed the revision, so hopefully that will work now. It shouldn't be dependent on anything solely in LakeEnsemblR to run just MyLake from this I think! Let me know if this issue (or another...) still persists!

**Comment by jjvenky** [comment]
The location of `mylake.Rdata` is still a problem:

```
> run_mylake(sim_folder=file.path(mylake_path,"extdata","example"))
Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
In addition: Warning message:
In readChar(con, 5L, useBytes = TRUE) :
  cannot open compressed file '/home/jason/R/x86_64-pc-linux-gnu-library/4.1/MyLakeR/extdata/example/MyLake/mylake.Rdata', probable reason 'No such file or directory'
```
The `mylake.Rdata` appears to be at `/home/jason/R/x86_64-pc-linux-gnu-library/4.1/MyLakeR/extdata/mylake.Rdata`. So the folder `example` may be the problem.

To ensure I've got the revised file, I've done `remove.packages("MyLakeR")`, restart R, and then `devtools::install_github("aemon-j/MyLakeR")`.

**Comment by rmpilla** [comment]
Okay I think I fixed this issue too -- I got it to run with this example on my machine with the latest patch. The file path was correct, but the final configuration file (revised in during config_mylake) has a different name that wasn't correct.

**Comment by jjvenky** [comment]
Success!
Thanks @rmpilla
